### PR TITLE
Correct typos

### PR DESCRIPTION
**Pull request by tanglie1993**

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
Hey there,

None of those corrections are actually typos. When you put "it's" instead of "its" you are essentially putting "it is" which does not work in any of those places. The concern is appreciated though!

**Comment by tanglie1993** [comment]
Hello,
The original file used "it's", and I proposed to write "its" instead.
@Jawnnypoo

**Comment by tanglie1993** [comment]
Hello,
The original file uses "it's", and I proposed to write "its" instead.
@Jawnnypoo

**Comment by Jawnnypoo** [comment]
Ahh wow, I was reading it backwards, apologies. Well, it seems like the repo has been deleted since so I am not able to reopen this PR

**Comment by tanglie1993** [comment]
I have created another PR, please merge it.
Thanks.
@Jawnnypoo

**Pull request closed without merging**
