### PR TITLE
Implement Swipe Dismiss on PhotoView.

### PR DESCRIPTION
**Pull request by WindSekirun**
Hi, I'm WindSekirun.

Our user requested 'Swipe Up or Down to dismiss image' function, but PhotoView already use their onTouchListener.

so, i merge My OnTouchListener and PhotoView's OnTouchListener and put some sample in SimpleSampleActivity.

it is just merge work, so process will be laggy some device. (and, it support API 15 and above)

### CODE REVIEW

**Comment by gobozov** [comment]
I used  photoView.setOnSingleFlingListener() to implement swipe to dismiss

**Comment by rubenmayayo** [comment]
> I used photoView.setOnSingleFlingListener() to implement swipe to dismiss

@gobozov could you explain how to do that? Thanks!

**Comment by thuongleit** [comment]
@rubenmayayo I believe the code will be:

```java
private static final int SWIPE_MIN_DISTANCE = 60;
private static final int SWIPE_THRESHOLD_VELOCITY = 100;

PhotoViewAttacher attacher = new PhotoViewAttacher(photoView);
attacher.setOnSingleFlingListener((e1, e2, velocityX, velocityY) -> {
           if (e1.getX() - e2.getX() > SWIPE_MIN_DISTANCE
					&& Math.abs(velocityX) > SWIPE_THRESHOLD_VELOCITY) {
				onRightToLeft();
				return true;
			} else if (e2.getX() - e1.getX() > SWIPE_MIN_DISTANCE
					&& Math.abs(velocityX) > SWIPE_THRESHOLD_VELOCITY) {
				onLeftToRight();
				return true;
			}
			if (e1.getY() - e2.getY() > SWIPE_MIN_DISTANCE
					&& Math.abs(velocityY) > SWIPE_THRESHOLD_VELOCITY) {
				onBottomToTop();
				return true;
			} else if (e2.getY() - e1.getY() > SWIPE_MIN_DISTANCE
					&& Math.abs(velocityY) > SWIPE_THRESHOLD_VELOCITY) {
				onTopToBottom();
				return true;
			}
    return false;
});
```

**Comment by Jawnnypoo** [comment]
Hi there, this looks neat, but I think it would be best to keep this out of the core library. Hopefully others who want to use this functionality can take a look at this PR to implement it themselves as well.

**Pull request closed without merging**
