### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by szhousun**
There is no 1.2.4 in Maven Central Repository.

### CODE REVIEW

**Comment by Fgabz** [comment]
Same for me  http://search.maven.org/#search%7Cga%7C1%7Cphotoview :/

**Comment by pmq** [comment]
Hi @smarek - do you know if 1.2.4 will be built and pushed to a Maven repo at some point? Thanks for your work!

**Comment by gelldur** [comment]
Same http://mvnrepository.com/artifact/com.github.chrisbanes.photoview/library

**Comment by smarek** [comment]
@pmq nope, sorry, this is up to Chris to do that, I never had the signature keys. You have to urge him directly, nothing I could do for you, sorry.

**Comment by pmq** [comment]
Thanks @smarek for the info. I guess we'll continue to consume our own builds.

**Comment by schwiz** [comment]
so frustrating this was never handled.

**Comment by danikula** [comment]
As simple workaround you can use [my repo](https://bintray.com/alexeydanilov/maven/PhotoView/view) instead of Maven Central for 1.2.4. Just add repo to repos list:

```
repositories {
    maven { url 'https://dl.bintray.com/alexeydanilov/maven' }
}
```

I just published the actual version (29 Apr 2015).

**Comment by maxme** [comment]
@chrisbanes any news on that? Can you publish the 1.2.4 version to maven central? Or give the keys to another maintainer?

**Comment by Jawnnypoo** [comment]
Maintenance has been turned over, the gradle dependency should work correctly now. Check the README for the latest.

**Pull request closed without merging**
