### PR TITLE
Adding CropTypeImage and initZoomAtMax to PhotoView attrs

### PR DESCRIPTION
**Pull request by jonathanrz**
Hi,
I don't know if this type of behaviour should be added to PhotoView library but I needed it and decided to implement in a fork and submit a PR, feel free to just ignore it :)

### CODE REVIEW

**Comment by arnaudbos** [comment]
+1 this should really be merged-in, I've just used the fork and after playing with the provided CustomScaleTypes I created one for my need (a mix of MATCH_HEIGHT with LEFT if imageWidth>viewWidth or CENTER if not).

**Comment by jonathanrz** [comment]
I saw that the PR should be merged to the develop branch and no master. I will change my PR to merge with the develop branch.

@arnaudbos I did not understand your first comment, can you tell me where this code should be me applied?

**Comment by arnaudbos** [comment]
Right [here](https://github.com/jonathanrz/PhotoView/commit/2c292fd73615ce77f9004e9cdf6bba276a774c29#commitcomment-15339372) if I'm not mistaken.

**Comment by arnaudbos** [comment]
Just out of curiosity, could you describe what the "initZoomAtMax" is for?
I have no use of it but I'm wondering what was/is your use case for creating it?

**Comment by Jawnnypoo** [comment]
PRs should be made against develop

**Pull request closed without merging**
