### PR TITLE
Fix post-Lollipop shared elements transition animations

### PR DESCRIPTION
**Pull request by Rexee**
Fix this issue: https://github.com/chrisbanes/PhotoView/issues/243
The main problem was that PhotoView does not override getImageMatrix
method, and when ChangeImageTransform call image.getImageMatrix() it
will receive matrix not from PhotoViewAttacher, but from PhotoView's
parent ImageView.

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
Ah wow, nice. I suppose I will have to take your word for it that it fixes it. Maybe I'll take some time to write a sample that shows it working. But thanks a bunch for your contribution!

**Comment by Rexee** [comment]
Yes, I highly recommend you to test it before releasing. It is possible that I return wrong matrix in PhotoViewAttacher. It looks right and working, but better recheck it twice.

**Comment by Jawnnypoo** [comment]
I went ahead and tested this and it looks good. Will release 1.2.8 soon with this fix

**Comment by Jawnnypoo** [comment]
Now available as 1.3.0

**Pull request merged**
