### PR TITLE
Allow parent intercept touches on top and bottom edges.

### PR DESCRIPTION
**Pull request by terrakok**
It needed for "scroll to dismiss" feature.

### CODE REVIEW

**Comment by terrakok** [comment]
@Jawnnypoo @chrisbanes  what do you think?

**Comment by Jawnnypoo** [comment]
Would you want to make a sample that shows this in action?

**Comment by Jawnnypoo** [comment]
Merge conflicts + can you create an example of scroll to dismiss for the sample app? Lots of people ask about it, so it would be great for the community. 😄

**Comment by terrakok** [comment]
We are waiting new PhotoView release 😎

**Pull request merged**
