### PR TITLE
Add getters to retrieve OnScaleChangeListener and OnSingleFlingListener

### PR DESCRIPTION
**Pull request by veyndan**

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
Can you think of a reason that you would want to be able to retrieve these later on? It is pretty uncommon to find in the Android system something like `setOnClickListener` and then later `getOnClickListener` typically, the activity or whatever else would just keep the reference around as needed.

**Comment by veyndan** [comment]
Hello, as this is my first contribution to GitHub I wanted to solve something trivial to get understand the process. I had noticed that another user had asked for getters for all the listeners (which I have only provided two so far), in order to trigger these actions in tests. [https://github.com/chrisbanes/PhotoView/issues/295](https://github.com/chrisbanes/PhotoView/issues/295)

**Comment by veyndan** [comment]
Out of interest, what is the purpose of `getOnPhotoTapListener` and `getOnViewTapListener()`?

**Comment by Jawnnypoo** [comment]
I really have no idea. They were contributions made before I started maintaining the library. But I suppose if some of these getters already exist then you might as well offer all of them.

**Comment by veyndan** [comment]
Wouldn't it be better to just deprecate these two methods, and eventually remove them from the library, due to the uselessness of these two methods? I don't know if adding unnecessary getters is preferable, due to the minor increase in bloatware for no perceivable gain.

**Comment by Jawnnypoo** [comment]
Yep, good point

**Comment by veyndan** [comment]
Would you like me to deprecate the two methods? Though I feel such a big decision should be done by you or one of the other previous contributors.

**Comment by Jawnnypoo** [comment]
Go for it. It is the right thing to do

**Pull request closed without merging**
