### PR TITLE
Remove android:allowBackup="true"

### PR DESCRIPTION
**Pull request by lkorth**
Allow apps using the library to select their own backup option without needing to override it.

### CODE REVIEW

**Comment by smarek** [comment]
Pull requests won't be merged into **master**

**Comment by smarek** [comment]
Also it's fixed in **dev**

**Comment by lkorth** [comment]
It may be worth noting in the README that pull requests should be submitted against `dev`, and/or changing the default branch to `dev`

**Comment by smarek** [comment]
That's correct, I'll update the README, thank you

**Pull request closed without merging**
