### PR TITLE
[PhotoView]: #409 fix setSystemuiVisibility bug

### PR DESCRIPTION
**Pull request by hyne-shan**
Plan: add conditions and add update
Type: bug
Test: test when use setSystemuiVisibility and SharedElement animation

### CODE REVIEW

**Comment by thmatew** [comment]
👍 
please merge it. It works and save our lives.

**Comment by Toubap** [comment]
This would be great to accept this PF which fixes an annoying behaviour..

**Comment by Jawnnypoo** [comment]
Can you give an example of when this is happening? I am happy to merge, I just do not know when exactly this is happening. There is a sample in this repo that uses Shared Element transitions and I am not seeing #409 happening as far as I can tell.

**Comment by Jawnnypoo** [comment]
Heya, `develop` is undergoing a lot of changes right now, so I am pulling this change in manually. Thanks for the PR though!

**Comment by Jawnnypoo** [comment]
Hey @hyne-shan I created a sample `ImmersiveActivity` and it seems like the zoom level is still getting reset when the system visibility is changed. Do you mind taking another look at this?

**Comment by hyne-shan** [comment]
@Jawnnypoo  the zoom level will reset when the system visibility is changed. 

the transition will shake when use share Shared Element Activity Transition  


I hope  you can merge it

@Override
    public Matrix getImageMatrix() {

        mAttacher.update();

        return mAttacher.getImageMatrix();
    }


if you hava  a same problem that you can try it

**Comment by Jawnnypoo** [comment]
@hyne-shan I had updated `getImageMatrix()` to include updating the attacher in the project, but it does not work with the ImmersiveActivity sample. Have you tried it there?

**Comment by hyne-shan** [comment]
ImmersiveActivity sample about when use setSystemuiVisibility


updated getImageMatrix() can fix  Shared Element issue

**Comment by hyne-shan** [comment]
sad   i update last version sdk

int viewid = View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                | View.SYSTEM_UI_FLAG_FULLSCREEN
                | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY;

decorView.setSystemUiVisibility(viewid);


setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);


it found  the zoom level is still getting reset when the system visibility is changed

**Comment by hyne-shan** [comment]
@Override
    public void onLayoutChange(View v, int left, int top, int right, int bottom, int oldLeft, int oldTop, int oldRight, int oldBottom) {
        // Update our base matrix, as the bounds have changed
        updateBaseMatrix(mImageView.getDrawable());
    }

the zoom will reset when layout change


you can add  mAttacher.update(); in getImageMatrix()

**Comment by Toubap** [comment]
We still have this issue by changing the window visibility (v. 2.0.0)

**Comment by anaszakariyah** [comment]
I also get the same issue. I am basing the layout from FullscreenActivity in Android Template Gallery which implement immersive experience. Hiding the SystemUI is okay but the bug occurs when SystemUI Visibility is shown again after being hidden.

**Comment by predasorinionut** [comment]
Hi. I am having the same issue when setting the fullscreen mode as @hyne-shan specified. I tried to solve this on my own with the following modification and it seems that it's working:

@Override
public void onLayoutChange(View v, int left, int top, int right, int bottom, int oldLeft, int oldTop, int oldRight, int oldBottom) {
    // Update our base matrix, as the bounds have changed
    if (left != oldLeft || top != oldTop || right != oldRight || bottom != oldBottom) {
        updateBaseMatrix(mImageView.getDrawable());
    }
}

Please verify my solution and if it's ok make a commit. This issue is very annoying and needs to be fixed.
Thanks.

**Pull request closed without merging**
